### ISSUE TITLE
Support for @Inherited annotations

### ISSUE THREAD

**Issue by doodla** [dropbox/hypershard-android#16]
Currently, it doesn't look like hypershard supports [`@Inherited`](https://docs.oracle.com/javase/7/docs/api/java/lang/annotation/Inherited.html) annotations.

As far as I see, hypershard is only parsing tests on a per-file basis without any knowledge of the hierarchy.

If superclasses could be queried for Annotations marked with `@Inherited` that would be cool.

**Comment by changusmc** [comment]
Hi @doodla, that's a great suggestion! If you're interested in adding this, I'd be happy to review a PR.

**Comment by changusmc** [comment]
Closing due to no response. This is not a feature that is currently needed internally, feel free to submit a PR and reopen this issue if the need arises.
