### ISSUE TITLE
Deps out of date

### ISSUE THREAD

**Issue by bootstraponline** [dropbox/hypershard-android#17]
Hey, we're working to add hypershard-android into Flank. The following deps are out of date and no longer developed.

```
implementation 'com.github.javaparser:javaparser-symbol-solver-core:3.6.25'
implementation 'com.github.cretz.kastree:kastree-ast-psi:0.1.0'
```

I think we can replace these with:

- https://github.com/javaparser/javaparser
- https://github.com/kotlinx/ast

Is there interest in reviewing/merging a pull request with this change?

**Comment by changusmc** [comment]
Hey, I'd be happy to review and merge a PR with this as long as all the tests pass
