### ISSUE TITLE
AST vs bytecode?

### ISSUE THREAD

**Issue by bootstraponline** [dropbox/hypershard-android#8]
I'd love to know more about why dropbox selected AST parsing compared to bytecode parsing. I think one advantage of bytecode parsing is it works with any language.

Does `hypershard-android` parse the AST for both Java and Kotlin?

https://github.com/linkedin/dex-test-parser

**Comment by changusmc** [comment]
Great question! 

On a high level, (1) we collect the tests on a single node in CI. That node will then give the list of tests and the scripts to run. (2) Then the our CI system will spin up N nodes and order the balance each node. Each node then will build the apk and test apk. 

In our internal CI system, it's not trivial to share artifacts between builds. Therefore, it's prudent (1) to be very fast. If we did bytecode parsing, it would slow down (1).

`hypershard-android` parses both Java and Kotlin, please see https://github.com/dropbox/hypershard-android/blob/master/src/main/kotlin/com/dropbox/mobile/hypershard/Hypershard.kt#L116-L205

**Comment by bootstraponline** [comment]
That makes perfect sense. Thanks for explaining!
